name: Build & Publish (main)

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
            java-version: 1.17
      - name: Gradle (Build)
        run: sh gradlew build
      - name: Upload artifacts (Main JAR)
        uses: actions/upload-artifact@v2
        with:
          name: Main JAR
          path: build/libs/*-all.jar
      - name: Upload artifacts (JARs)
        uses: actions/upload-artifact@v2
        with:
          name: JARs
          path: build/libs/*.jar
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: docker build -t ghcr.io/smalauncher/smarollingscraper:latest -t ghcr.io/smalauncher/smarollingscraper:${GITHUB_SHA} .
      - run: docker push ghcr.io/smalauncher/smarollingscraper:latest
      - run: docker push ghcr.io/smalauncher/smarollingscraper:${GITHUB_SHA}
#      - name: Install SSH key
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.GSERV_SSH_KEY }}
#          known_hosts: ${{ secrets.GSERV_SSH_KNOWN_HOSTS }}
#      - name: Apply new release to gdude's server
#        run: ssh ${{ secrets.GSERV_SSH_USER }}@${{ secrets.GSERV_SSH_HOST }} -p ${{ secrets.GSERV_SSH_PORT }} sudo /home/leo40/deploy-scraper.sh
